name: Publish

on:
  release:
    types: [ published ]

jobs:
  deploy:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Publish release
        run: |
          ./gradlew clean publish -Pversion=${{ github.event.release.tag_name }}

      - name: Update snapshot version
        run: |
          ./gradlew updateVersion -PreleaseVersion=${{ github.event.release.tag_name }} --rerun-tasks

      - name: Commit gradle.properties
        run: |
          git config --global user.name 'truffle-kotlin'
          git config --global user.email 'truffle-kotlin@wafflestudio.com'
          git fetch
          git checkout master
          git add ./gradle.properties
          git commit -m "Automated commit by GitHub Actions"
          git push
