name: Publish

on:
  release:
    types: [ published ]

jobs:
  deploy:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Get AWS CodeArtifact auth token
        run: |
          echo "auth_token=$(aws codeartifact get-authorization-token \
            --domain wafflestudio --domain-owner 405906814034 \
            --query authorizationToken --region ap-northeast-1)" \
            >> $GITHUB_ENV

      - name: Publish release
        run: |
          ./gradlew clean publish -PauthToken=${{ env.auth_token }} -Pversion=${{ github.event.release.tag_name }}

      - name: Update snapshot version
        run: |
          ./gradlew updateVersion -Pversion=${{ github.event.release.tag_name }} --rerun-tasks

      - name: Commit gradle.properties
        run: |
          git config --global user.name 'truffle-kotlin'
          git config --global user.email 'truffle-kotlin@wafflestudio.com'
          git add ./gradle.properties
          git commit -m "Automated commit by GitHub Actions"
          git push
